//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolBytes.ScriptInterpreter.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoolBytes.ScriptInterpreter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute.
        /// </summary>
        public static string BTN_EXECUTE {
            get {
                return ResourceManager.GetString("BTN_EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load state previously saved.
        /// </summary>
        public static string BTN_LOAD_STATE {
            get {
                return ResourceManager.GetString("BTN_LOAD_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load.
        /// </summary>
        public static string BTN_LOADSCRIPT {
            get {
                return ResourceManager.GetString("BTN_LOADSCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify list of using/imports.
        /// </summary>
        public static string BTN_MODITY_LIST_USINGS {
            get {
                return ResourceManager.GetString("BTN_MODITY_LIST_USINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string BTN_SAVESCRIPT {
            get {
                return ResourceManager.GetString("BTN_SAVESCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intellisense.
        /// </summary>
        public static string CHK_INTELLISENSE {
            get {
                return ResourceManager.GetString("CHK_INTELLISENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open a window.
        /// </summary>
        public static string CHK_OPEN_WINDOW {
            get {
                return ResourceManager.GetString("CHK_OPEN_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute in another thread.
        /// </summary>
        public static string CHK_OTHERTHREAD {
            get {
                return ResourceManager.GetString("CHK_OTHERTHREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read fields.
        /// </summary>
        public static string CHK_READ_FIELDS {
            get {
                return ResourceManager.GetString("CHK_READ_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read public properties.
        /// </summary>
        public static string CHK_READ_PUBLIC_PROPERTY {
            get {
                return ResourceManager.GetString("CHK_READ_PUBLIC_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Serialization by DataContract.
        /// </summary>
        public static string CHK_SERIALIZATION_DATACONTACT {
            get {
                return ResourceManager.GetString("CHK_SERIALIZATION_DATACONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à With inherits.
        /// </summary>
        public static string CHK_WITH_INHERITS {
            get {
                return ResourceManager.GetString("CHK_WITH_INHERITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System
        ///System.Linq.
        /// </summary>
        public static string DEFAULTS_USING {
            get {
                return ResourceManager.GetString("DEFAULTS_USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during executing script.
        /// </summary>
        public static string ERROR_EXECUTE_SCRIPT {
            get {
                return ResourceManager.GetString("ERROR_EXECUTE_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during loading objet state from file. Erreur : .
        /// </summary>
        public static string ERROR_LOAD_STATE {
            get {
                return ResourceManager.GetString("ERROR_LOAD_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during try to save script to disk.
        /// </summary>
        public static string ERROR_SAVE_SCRIPT {
            get {
                return ResourceManager.GetString("ERROR_SAVE_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during serialization of object : .
        /// </summary>
        public static string ERROR_SERIALIZATION {
            get {
                return ResourceManager.GetString("ERROR_SERIALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Error(s) :&quot;.
        /// </summary>
        public static string ERRORS {
            get {
                return ResourceManager.GetString("ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DataContract name :.
        /// </summary>
        public static string LBL_DATACONTRACT_NAME {
            get {
                return ResourceManager.GetString("LBL_DATACONTRACT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max recursive :.
        /// </summary>
        public static string LBL_MAX_RECURSIVE {
            get {
                return ResourceManager.GetString("LBL_MAX_RECURSIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Result :.
        /// </summary>
        public static string LBL_RESULT {
            get {
                return ResourceManager.GetString("LBL_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comments.
        /// </summary>
        public static string LINK_COMMENTARY {
            get {
                return ResourceManager.GetString("LINK_COMMENTARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fields.
        /// </summary>
        public static string LINK_FIELD {
            get {
                return ResourceManager.GetString("LINK_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Methods.
        /// </summary>
        public static string LINK_METHOD {
            get {
                return ResourceManager.GetString("LINK_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Namespace.
        /// </summary>
        public static string LINK_NAMESPACE {
            get {
                return ResourceManager.GetString("LINK_NAMESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties.
        /// </summary>
        public static string LINK_PROPERTY {
            get {
                return ResourceManager.GetString("LINK_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse all.
        /// </summary>
        public static string MENUITEM_COLLAPSE_ALL {
            get {
                return ResourceManager.GetString("MENUITEM_COLLAPSE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        public static string MENUITEM_COPY {
            get {
                return ResourceManager.GetString("MENUITEM_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy the value.
        /// </summary>
        public static string MENUITEM_COPY_VALUE {
            get {
                return ResourceManager.GetString("MENUITEM_COPY_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cut.
        /// </summary>
        public static string MENUITEM_CUT {
            get {
                return ResourceManager.GetString("MENUITEM_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expand all.
        /// </summary>
        public static string MENUITEM_EXPAND_ALL {
            get {
                return ResourceManager.GetString("MENUITEM_EXPAND_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste.
        /// </summary>
        public static string MENUITEM_PASTE {
            get {
                return ResourceManager.GetString("MENUITEM_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save state.
        /// </summary>
        public static string MENUITEM_SAVE_STATE {
            get {
                return ResourceManager.GetString("MENUITEM_SAVE_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select all.
        /// </summary>
        public static string MENUITEM_SELECT_ALL {
            get {
                return ResourceManager.GetString("MENUITEM_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Script executed, return : .
        /// </summary>
        public static string SCRIPT_OK_RETURN {
            get {
                return ResourceManager.GetString("SCRIPT_OK_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Script executed, do not return value.
        /// </summary>
        public static string SCRIPT_RETURN_VOID {
            get {
                return ResourceManager.GetString("SCRIPT_RETURN_VOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Script interpreter in Net Framework.
        /// </summary>
        public static string WINDOW_TITLE {
            get {
                return ResourceManager.GetString("WINDOW_TITLE", resourceCulture);
            }
        }
    }
}
