using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Explorip")]
[assembly: InternalsVisibleTo("Explorip.Desktop")]
[assembly: InternalsVisibleTo("Explorip.StartMenu")]
[assembly: InternalsVisibleTo("Explorip.Taskbar")]
[assembly: InternalsVisibleTo("ManagedShell.AppBar")]
[assembly: InternalsVisibleTo("ManagedShell.Common")]
[assembly: InternalsVisibleTo("ManagedShell.WindowsTasks")]
[assembly: InternalsVisibleTo("ManagedShell.WindowsTray")]
[assembly: InternalsVisibleTo("ManagedShell")]
[assembly: InternalsVisibleTo("ManagedShell.ShellFolders")]
[assembly: InternalsVisibleTo("HookFileOperations")]
[assembly: InternalsVisibleTo("ExploripCopy")]
[assembly: InternalsVisibleTo("ExploripComponents")]
