//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAPICodePack.Shell.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedMessages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAPICodePack.Shell.Resources.LocalizedMessages", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AddToMostRecentlyUsedList cannot be changed while dialog is showing..
        /// </summary>
        internal static string AddToMostRecentlyUsedListCannotBeChanged {
            get {
                return ResourceManager.GetString("AddToMostRecentlyUsedListCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AlwaysAppendDefaultExtension cannot be changed while dialog is showing..
        /// </summary>
        internal static string AlwaysAppendDefaultExtensionCannotBeChanged {
            get {
                return ResourceManager.GetString("AlwaysAppendDefaultExtensionCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index was outside the bounds of the CommonFileDialogComboBox..
        /// </summary>
        internal static string ComboBoxIndexOutsideBounds {
            get {
                return ResourceManager.GetString("ComboBoxIndexOutsideBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File name not available - dialog was canceled..
        /// </summary>
        internal static string CommonFileDialogCanceled {
            get {
                return ResourceManager.GetString("CommonFileDialogCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shell item could not be created..
        /// </summary>
        internal static string CommonFileDialogCannotCreateShellItem {
            get {
                return ResourceManager.GetString("CommonFileDialogCannotCreateShellItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Handle provided cannot be IntPtr.Zero..
        /// </summary>
        internal static string CommonFileDialogInvalidHandle {
            get {
                return ResourceManager.GetString("CommonFileDialogInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Multiple files selected - the FileNames property should be used instead..
        /// </summary>
        internal static string CommonFileDialogMultipleFiles {
            get {
                return ResourceManager.GetString("CommonFileDialogMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Multiple files selected - the Items property should be used instead..
        /// </summary>
        internal static string CommonFileDialogMultipleItems {
            get {
                return ResourceManager.GetString("CommonFileDialogMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File name not available - dialog has not closed yet..
        /// </summary>
        internal static string CommonFileDialogNotClosed {
            get {
                return ResourceManager.GetString("CommonFileDialogNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Common File Dialog requires Windows Vista or later..
        /// </summary>
        internal static string CommonFileDialogRequiresVista {
            get {
                return ResourceManager.GetString("CommonFileDialogRequiresVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Office Files.
        /// </summary>
        internal static string CommonFiltersOffice {
            get {
                return ResourceManager.GetString("CommonFiltersOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All Picture Files.
        /// </summary>
        internal static string CommonFiltersPicture {
            get {
                return ResourceManager.GetString("CommonFiltersPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text Files.
        /// </summary>
        internal static string CommonFiltersText {
            get {
                return ResourceManager.GetString("CommonFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CreatePrompt cannot be changed while dialog is showing..
        /// </summary>
        internal static string CreatePromptCannotBeChanged {
            get {
                return ResourceManager.GetString("CreatePromptCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom controls cannot be removed from a File dialog once added..
        /// </summary>
        internal static string DialogControlCollectionCannotRemoveControls {
            get {
                return ResourceManager.GetString("DialogControlCollectionCannotRemoveControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Control name cannot be null or zero length..
        /// </summary>
        internal static string DialogControlCollectionEmptyName {
            get {
                return ResourceManager.GetString("DialogControlCollectionEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CommonFileDialogMenuItem controls can only be added to CommonFileDialogMenu controls..
        /// </summary>
        internal static string DialogControlCollectionMenuItemControlsCannotBeAdded {
            get {
                return ResourceManager.GetString("DialogControlCollectionMenuItemControlsCannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifying controls collection while dialog is showing is not supported..
        /// </summary>
        internal static string DialogControlCollectionModifyingControls {
            get {
                return ResourceManager.GetString("DialogControlCollectionModifyingControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dialog cannot have more than one control with the same name..
        /// </summary>
        internal static string DialogControlCollectionMoreThanOneControl {
            get {
                return ResourceManager.GetString("DialogControlCollectionMoreThanOneControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dialog control must be removed from current collections first..
        /// </summary>
        internal static string DialogControlCollectionRemoveControlFirst {
            get {
                return ResourceManager.GetString("DialogControlCollectionRemoveControlFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EnsureFileExists cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsureFileExistsCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureFileExistsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EnsurePathExists cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsurePathExistsCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsurePathExistsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EnsureReadOnly cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsureReadonlyCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureReadonlyCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EnsureValidNames cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsureValidNamesCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureValidNamesCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browsing to object failed..
        /// </summary>
        internal static string ExplorerBrowserBrowseToObjectFailed {
            get {
                return ResourceManager.GetString("ExplorerBrowserBrowseToObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ExplorerBrowser failed to get current view..
        /// </summary>
        internal static string ExplorerBrowserFailedToGetView {
            get {
                return ResourceManager.GetString("ExplorerBrowserFailedToGetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to get icon size..
        /// </summary>
        internal static string ExplorerBrowserIconSize {
            get {
                return ResourceManager.GetString("ExplorerBrowserIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unexpected error retrieving item count..
        /// </summary>
        internal static string ExplorerBrowserItemCount {
            get {
                return ResourceManager.GetString("ExplorerBrowserItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unexpected error retrieving selected item count..
        /// </summary>
        internal static string ExplorerBrowserSelectedItemCount {
            get {
                return ResourceManager.GetString("ExplorerBrowserSelectedItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unexpected error retrieving selection..
        /// </summary>
        internal static string ExplorerBrowserUnexpectedError {
            get {
                return ResourceManager.GetString("ExplorerBrowserUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unexpected error retrieving view items..
        /// </summary>
        internal static string ExplorerBrowserViewItems {
            get {
                return ResourceManager.GetString("ExplorerBrowserViewItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The given path does not exist ({0}).
        /// </summary>
        internal static string FilePathNotExist {
            get {
                return ResourceManager.GetString("FilePathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guid does not identify a known folder..
        /// </summary>
        internal static string FolderIdsUnknownGuid {
            get {
                return ResourceManager.GetString("FolderIdsUnknownGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ControlPanel Category.
        /// </summary>
        internal static string FolderTypeCategory {
            get {
                return ResourceManager.GetString("FolderTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ControlPanel Classic.
        /// </summary>
        internal static string FolderTypeClassic {
            get {
                return ResourceManager.GetString("FolderTypeClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Communications.
        /// </summary>
        internal static string FolderTypeCommunications {
            get {
                return ResourceManager.GetString("FolderTypeCommunications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compressed Folder.
        /// </summary>
        internal static string FolderTypeCompressedFolder {
            get {
                return ResourceManager.GetString("FolderTypeCompressedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contacts.
        /// </summary>
        internal static string FolderTypeContacts {
            get {
                return ResourceManager.GetString("FolderTypeContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Documents.
        /// </summary>
        internal static string FolderTypeDocuments {
            get {
                return ResourceManager.GetString("FolderTypeDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Games.
        /// </summary>
        internal static string FolderTypeGames {
            get {
                return ResourceManager.GetString("FolderTypeGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generic Library.
        /// </summary>
        internal static string FolderTypeGenericLibrary {
            get {
                return ResourceManager.GetString("FolderTypeGenericLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid.
        /// </summary>
        internal static string FolderTypeInvalid {
            get {
                return ResourceManager.GetString("FolderTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Library.
        /// </summary>
        internal static string FolderTypeLibrary {
            get {
                return ResourceManager.GetString("FolderTypeLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music.
        /// </summary>
        internal static string FolderTypeMusic {
            get {
                return ResourceManager.GetString("FolderTypeMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music Icons.
        /// </summary>
        internal static string FolderTypeMusicIcons {
            get {
                return ResourceManager.GetString("FolderTypeMusicIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Network Explorer.
        /// </summary>
        internal static string FolderTypeNetworkExplorer {
            get {
                return ResourceManager.GetString("FolderTypeNetworkExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not Specified.
        /// </summary>
        internal static string FolderTypeNotSpecified {
            get {
                return ResourceManager.GetString("FolderTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Search.
        /// </summary>
        internal static string FolderTypeOpenSearch {
            get {
                return ResourceManager.GetString("FolderTypeOpenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Other Users.
        /// </summary>
        internal static string FolderTypeOtherUsers {
            get {
                return ResourceManager.GetString("FolderTypeOtherUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pictures.
        /// </summary>
        internal static string FolderTypePictures {
            get {
                return ResourceManager.GetString("FolderTypePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Printers.
        /// </summary>
        internal static string FolderTypePrinters {
            get {
                return ResourceManager.GetString("FolderTypePrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RecordedTV.
        /// </summary>
        internal static string FolderTypeRecordedTV {
            get {
                return ResourceManager.GetString("FolderTypeRecordedTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RecycleBin.
        /// </summary>
        internal static string FolderTypeRecycleBin {
            get {
                return ResourceManager.GetString("FolderTypeRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saved Games.
        /// </summary>
        internal static string FolderTypeSavedGames {
            get {
                return ResourceManager.GetString("FolderTypeSavedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search Connector.
        /// </summary>
        internal static string FolderTypeSearchConnector {
            get {
                return ResourceManager.GetString("FolderTypeSearchConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Searches.
        /// </summary>
        internal static string FolderTypeSearches {
            get {
                return ResourceManager.GetString("FolderTypeSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generic SearchResults.
        /// </summary>
        internal static string FolderTypeSearchResults {
            get {
                return ResourceManager.GetString("FolderTypeSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Software Explorer.
        /// </summary>
        internal static string FolderTypeSoftwareExplorer {
            get {
                return ResourceManager.GetString("FolderTypeSoftwareExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Files.
        /// </summary>
        internal static string FolderTypeUserFiles {
            get {
                return ResourceManager.GetString("FolderTypeUserFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users Libraries.
        /// </summary>
        internal static string FolderTypeUserLibraries {
            get {
                return ResourceManager.GetString("FolderTypeUserLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Videos.
        /// </summary>
        internal static string FolderTypeVideos {
            get {
                return ResourceManager.GetString("FolderTypeVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IsExpandedMode cannot be changed while dialog is showing..
        /// </summary>
        internal static string IsExpandedModeCannotBeChanged {
            get {
                return ResourceManager.GetString("IsExpandedModeCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom categories cannot be added while recent documents tracking is turned off..
        /// </summary>
        internal static string JumpListCustomCategoriesDisabled {
            get {
                return ResourceManager.GetString("JumpListCustomCategoriesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file type is not registered with this application..
        /// </summary>
        internal static string JumpListFileTypeNotRegistered {
            get {
                return ResourceManager.GetString("JumpListFileTypeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JumpListLink&apos;s path is required and cannot be null..
        /// </summary>
        internal static string JumpListLinkPathRequired {
            get {
                return ResourceManager.GetString("JumpListLinkPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JumpListLink&apos;s title is required and cannot be null..
        /// </summary>
        internal static string JumpListLinkTitleRequired {
            get {
                return ResourceManager.GetString("JumpListLinkTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Negative numbers are not allowed for the ordinal position..
        /// </summary>
        internal static string JumpListNegativeOrdinalPosition {
            get {
                return ResourceManager.GetString("JumpListNegativeOrdinalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Given Known Folder ID is invalid..
        /// </summary>
        internal static string KnownFolderInvalidGuid {
            get {
                return ResourceManager.GetString("KnownFolderInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parsing name is invalid..
        /// </summary>
        internal static string KnownFolderParsingName {
            get {
                return ResourceManager.GetString("KnownFolderParsingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation of window has failed, view inner exception for details..
        /// </summary>
        internal static string MessageListenerCannotCreateWindow {
            get {
                return ResourceManager.GetString("MessageListenerCannotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Window class could not be registered, check inner exception for more details..
        /// </summary>
        internal static string MessageListenerClassNotRegistered {
            get {
                return ResourceManager.GetString("MessageListenerClassNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message filter registration failed..
        /// </summary>
        internal static string MessageListenerFilterUnableToRegister {
            get {
                return ResourceManager.GetString("MessageListenerFilterUnableToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No listener handled of that value is registered..
        /// </summary>
        internal static string MessageListenerFilterUnknownListenerHandle {
            get {
                return ResourceManager.GetString("MessageListenerFilterUnknownListenerHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot create window on the listener thread because there is no existing window on the listener thread..
        /// </summary>
        internal static string MessageListenerNoWindowHandle {
            get {
                return ResourceManager.GetString("MessageListenerNoWindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NavigateToShortcut cannot be changed while dialog is showing..
        /// </summary>
        internal static string NavigateToShortcutCannotBeChanged {
            get {
                return ResourceManager.GetString("NavigateToShortcutCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parent cannot be null..
        /// </summary>
        internal static string NavigationLogNullParent {
            get {
                return ResourceManager.GetString("NavigationLogNullParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The method or operation is not implemented..
        /// </summary>
        internal static string NotImplementedException {
            get {
                return ResourceManager.GetString("NotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OverwritePrompt cannot be changed while dialog is showing..
        /// </summary>
        internal static string OverwritePromptCannotBeChanged {
            get {
                return ResourceManager.GetString("OverwritePromptCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This CanonicalName is not a valid index..
        /// </summary>
        internal static string PropertyCollectionCanonicalInvalidIndex {
            get {
                return ResourceManager.GetString("PropertyCollectionCanonicalInvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This PropertyKey is not a valid index..
        /// </summary>
        internal static string PropertyCollectionInvalidIndex {
            get {
                return ResourceManager.GetString("PropertyCollectionInvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Argument CanonicalName cannot be null or empty..
        /// </summary>
        internal static string PropertyCollectionNullCanonicalName {
            get {
                return ResourceManager.GetString("PropertyCollectionNullCanonicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index was outside the bounds of the CommonFileDialogRadioButtonList..
        /// </summary>
        internal static string RadioButtonListIndexOutOfBounds {
            get {
                return ResourceManager.GetString("RadioButtonListIndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RestoreDirectory cannot be changed while dialog is showing..
        /// </summary>
        internal static string RestoreDirectoryCannotBeChanged {
            get {
                return ResourceManager.GetString("RestoreDirectoryCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieved a null shell item from dialog..
        /// </summary>
        internal static string SaveFileNullItem {
            get {
                return ResourceManager.GetString("SaveFileNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Given property key is invalid..
        /// </summary>
        internal static string SearchConditionFactoryInvalidProperty {
            get {
                return ResourceManager.GetString("SearchConditionFactoryInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shell Exception has occurred, look at inner exception for information..
        /// </summary>
        internal static string ShellExceptionDefaultText {
            get {
                return ResourceManager.GetString("ShellExceptionDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GetParsingName has failed..
        /// </summary>
        internal static string ShellHelperGetParsingNameFailed {
            get {
                return ResourceManager.GetString("ShellHelperGetParsingNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The given CanonicalName is not valid..
        /// </summary>
        internal static string ShellInvalidCanonicalName {
            get {
                return ResourceManager.GetString("ShellInvalidCanonicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DefaultSaveFolder path not found..
        /// </summary>
        internal static string ShellLibraryDefaultSaveFolderNotFound {
            get {
                return ResourceManager.GetString("ShellLibraryDefaultSaveFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LibraryName cannot be empty..
        /// </summary>
        internal static string ShellLibraryEmptyName {
            get {
                return ResourceManager.GetString("ShellLibraryEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folder path not found..
        /// </summary>
        internal static string ShellLibraryFolderNotFound {
            get {
                return ResourceManager.GetString("ShellLibraryFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid FolderType Guid..
        /// </summary>
        internal static string ShellLibraryInvalidFolderType {
            get {
                return ResourceManager.GetString("ShellLibraryInvalidFolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The given known folder is not a valid library..
        /// </summary>
        internal static string ShellLibraryInvalidLibrary {
            get {
                return ResourceManager.GetString("ShellLibraryInvalidLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t get the display name..
        /// </summary>
        internal static string ShellObjectCannotGetDisplayName {
            get {
                return ResourceManager.GetString("ShellObjectCannotGetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination array too small, or invalid arrayIndex..
        /// </summary>
        internal static string ShellObjectCollectionArrayTooSmall {
            get {
                return ResourceManager.GetString("ShellObjectCollectionArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Must have at least one shell object in the collection..
        /// </summary>
        internal static string ShellObjectCollectionEmptyCollection {
            get {
                return ResourceManager.GetString("ShellObjectCollectionEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot insert items into a read only list..
        /// </summary>
        internal static string ShellObjectCollectionInsertReadOnly {
            get {
                return ResourceManager.GetString("ShellObjectCollectionInsertReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot remove items from a read only list..
        /// </summary>
        internal static string ShellObjectCollectionRemoveReadOnly {
            get {
                return ResourceManager.GetString("ShellObjectCollectionRemoveReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shell item could not be created..
        /// </summary>
        internal static string ShellObjectCreationFailed {
            get {
                return ResourceManager.GetString("ShellObjectCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shell Object creation requires Windows Vista or higher operating system..
        /// </summary>
        internal static string ShellObjectFactoryPlatformNotSupported {
            get {
                return ResourceManager.GetString("ShellObjectFactoryPlatformNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to Create Shell Item..
        /// </summary>
        internal static string ShellObjectFactoryUnableToCreateItem {
            get {
                return ResourceManager.GetString("ShellObjectFactoryUnableToCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registration for change notification has failed..
        /// </summary>
        internal static string ShellObjectWatcherRegisterFailed {
            get {
                return ResourceManager.GetString("ShellObjectWatcherRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to change watched events while listening..
        /// </summary>
        internal static string ShellObjectWatcherUnableToChangeEvents {
            get {
                return ResourceManager.GetString("ShellObjectWatcherUnableToChangeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The value on this property cannot be set. To set the property value, use the ShellObject that is associated with this property..
        /// </summary>
        internal static string ShellPropertyCannotSetProperty {
            get {
                return ResourceManager.GetString("ShellPropertyCannotSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No constructor found matching requested argument types..
        /// </summary>
        internal static string ShellPropertyFactoryConstructorNotFound {
            get {
                return ResourceManager.GetString("ShellPropertyFactoryConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to set property..
        /// </summary>
        internal static string ShellPropertySetValue {
            get {
                return ResourceManager.GetString("ShellPropertySetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to get writable property store for this property..
        /// </summary>
        internal static string ShellPropertyUnableToGetWritableProperty {
            get {
                return ResourceManager.GetString("ShellPropertyUnableToGetWritableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A value had to be truncated in a string or rounded if a numeric value. Set AllowTruncatedValue to true to prevent this exception..
        /// </summary>
        internal static string ShellPropertyValueTruncated {
            get {
                return ResourceManager.GetString("ShellPropertyValueTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This Property is available on Windows 7 only..
        /// </summary>
        internal static string ShellPropertyWindows7 {
            get {
                return ResourceManager.GetString("ShellPropertyWindows7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This property only accepts a value of type \&quot;{0}\&quot;..
        /// </summary>
        internal static string ShellPropertyWrongType {
            get {
                return ResourceManager.GetString("ShellPropertyWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to set list of sort columns..
        /// </summary>
        internal static string ShellSearchFolderUnableToSetSortColumns {
            get {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetSortColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to set visible columns..
        /// </summary>
        internal static string ShellSearchFolderUnableToSetVisibleColumns {
            get {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetVisibleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CurrentSize (width or height) cannot be greater than the maximum size: {0}..
        /// </summary>
        internal static string ShellThumbnailCurrentSizeRange {
            get {
                return ResourceManager.GetString("ShellThumbnailCurrentSizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The current ShellObject does not have a thumbnail. Try using ShellThumbnailFormatOption.Default to get the icon for this item..
        /// </summary>
        internal static string ShellThumbnailDoesNotHaveThumbnail {
            get {
                return ResourceManager.GetString("ShellThumbnailDoesNotHaveThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The current ShellObject does not have a valid thumbnail handler or there was a problem in extracting the thumbnail for this specific shell object..
        /// </summary>
        internal static string ShellThumbnailNoHandler {
            get {
                return ResourceManager.GetString("ShellThumbnailNoHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CurrentSize (width or height) cannot be 0..
        /// </summary>
        internal static string ShellThumbnailSizeCannotBe0 {
            get {
                return ResourceManager.GetString("ShellThumbnailSizeCannotBe0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ShowHiddenItems cannot be changed while dialog is showing..
        /// </summary>
        internal static string ShowHiddenItemsCannotBeChanged {
            get {
                return ResourceManager.GetString("ShowHiddenItemsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show places list cannot be changed while dialog is showing..
        /// </summary>
        internal static string ShowPlacesListCannotBeChanged {
            get {
                return ResourceManager.GetString("ShowPlacesListCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Stock Icon identifier given is invalid ({0})..
        /// </summary>
        internal static string StockIconInvalidGuid {
            get {
                return ResourceManager.GetString("StockIconInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Child control&apos;s window handle cannot be zero..
        /// </summary>
        internal static string TabbedThumbnailZeroChildHandle {
            get {
                return ResourceManager.GetString("TabbedThumbnailZeroChildHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parent window handle cannot be zero..
        /// </summary>
        internal static string TabbedThumbnailZeroParentHandle {
            get {
                return ResourceManager.GetString("TabbedThumbnailZeroParentHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TabbedThumbnailProxyWindow has not been set..
        /// </summary>
        internal static string TasbarWindowProxyWindowSet {
            get {
                return ResourceManager.GetString("TasbarWindowProxyWindowSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A valid active Window is needed to update the Taskbar..
        /// </summary>
        internal static string TaskbarManagerValidWindowRequired {
            get {
                return ResourceManager.GetString("TaskbarManagerValidWindowRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The array of buttons must contain at least 1 item..
        /// </summary>
        internal static string TaskbarWindowEmptyButtonArray {
            get {
                return ResourceManager.GetString("TaskbarWindowEmptyButtonArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tool bar buttons for this window are already added. Please refer to the Remarks section of the AddButtons method for more information on updating the properties or hiding existing buttons..
        /// </summary>
        internal static string TaskbarWindowManagerButtonsAlreadyAdded {
            get {
                return ResourceManager.GetString("TaskbarWindowManagerButtonsAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value is already set. It cannot be set more than once..
        /// </summary>
        internal static string TaskbarWindowValueSet {
            get {
                return ResourceManager.GetString("TaskbarWindowValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The given control has not been added to the taskbar..
        /// </summary>
        internal static string ThumbnailManagerControlNotAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerControlNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Window handle is invalid..
        /// </summary>
        internal static string ThumbnailManagerInvalidHandle {
            get {
                return ResourceManager.GetString("ThumbnailManagerInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This preview has already been added..
        /// </summary>
        internal static string ThumbnailManagerPreviewAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerPreviewAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The given preview has not been added to the taskbar..
        /// </summary>
        internal static string ThumbnailManagerPreviewNotAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerPreviewNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum number of buttons allowed is 7..
        /// </summary>
        internal static string ThumbnailToolbarManagerMaxButtons {
            get {
                return ResourceManager.GetString("ThumbnailToolbarManagerMaxButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Null or empty arrays are not allowed..
        /// </summary>
        internal static string ThumbnailToolbarManagerNullEmptyArray {
            get {
                return ResourceManager.GetString("ThumbnailToolbarManagerNullEmptyArray", resourceCulture);
            }
        }
    }
}
